services:
  nerl-api:
    build: . # builds using the ./Dockerfile
    user: root
    environment:
      CUDA_VISIBLE_DEVICES: ""
      LANGUAGE: es
    ports:
      - "5000:5000"
    volumes:
      - ./app:/NERL_API/app   # map local /app to container container /app
    restart: unless-stopped
    privileged: true

networks:
  default:
    name: cogstack-net
    external: true